version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ums_test_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - test_ums_data:/var/lib/postgresql/test_ums_data

volumes:
  test_ums_data:
