version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ums_test_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - test_ums_data:/var/lib/postgresql/test_ums_data

volumes:
  test_ums_data:
